### ISSUE TITLE
about Multi-Scale Information Correlation Mining Block

### ISSUE THREAD

**Issue by nimuyc** [Hua-XC/MSCMNet#2]
dear author, I'm very interested in Multi-Scale Information Correlation Mining Block in your article, but after reading the code, I haven't found something about this. Would you tell me where is it?

**Comment by Hua-XC** [comment]
The title of the article is "Multi-scale Semantic Correlation Mining for Visible-Infrared Person Re-Identification" on arxiv

**Comment by Hua-XC** [comment]
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4761606

**Comment by nimuyc** [comment]
thank you for your answer, dear author. I made a mistake just now. sorry!

**Comment by Hua-XC** [comment]
good luck



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 21, 2024 16:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Hua-XC/MSCMNet] about Multi-Scale Information Correlation MiningBlock (Issue #2)




 
thank you for your answer, dear author. I made a mistake just now. sorry!
