### ISSUE TITLE
你好，感谢你的工作，tsne和ranking相关的代码方便提供吗？

### ISSUE THREAD

**Issue by yhl2018** [Hua-XC/MSCMNet#3]

**Comment by Hua-XC** [comment]
Hello, thank you for your question. Our visual method interface is in the VisualizeH folder. For specific implementation, you need to call these methods in your project.

**Comment by yhl2018** [comment]
十分感谢，针对您文章中的一些可视化的方式，方便提供一些demo吗？调用这些接口的demo？

**Comment by liudongcan666** [comment]
![Image](https://github.com/user-attachments/assets/8c119457-7f54-4342-ba30-43e6792feb37)  你好，这是一个很优秀的工作，但是我有一些问题，数据在train时表现良好，但是我用
python test.py --dataset sysu --mode all --resume save_model/sysu/$VERSION/sysu_mscm_p4_n6_lr_0.1_seed_0_best.t
python test.py --dataset sysu --mode indoor --resume save_model/sysu/$VERSION/sysu_mscm_p4_n6_lr_0.1_seed_0_best.t
来验证数据时，效果很差，并且测试的日志也无法保存，请问时什么原因？

![Image](https://github.com/user-attachments/assets/6f834a11-85a7-4c93-a194-4b9c2b4e3af2) 感谢解答！！！
