### ISSUE TITLE
很棒的工作！关于红外光图像数据增强有一些疑问

### ISSUE THREAD

**Issue by Mona12138** [Hua-XC/MSCMNet#4]
对于红外光来说，三个通道的数值相同。
请问，通过您channel_aug.py中的class ChannelAdapGray怎么进行通道增强啊..
结果都是返回原图..

**Comment by Hua-XC** [comment]
Hello! ChannelAdapGray technique is cited by the "Channel Augmented Joint Learning for Visible-Infrared Recognition" paper(https://github.com/mangye16/Cross-Modal-Re-ID-baseline/tree/master/ICCV21_CAJ), and the proposed ChannelT endows IR images with some channel information.&nbsp;Thank you for researching our work！Good luck！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hua-XC/MSCMNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月4日(星期四) 下午4:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Hua-XC/MSCMNet] 很棒的工作！关于红外光图像数据增强有一些疑问 (Issue #4)





 
对于红外光来说，三个通道的数值相同。
 请问，通过您channel_aug.py中的class ChannelAdapGray怎么进行通道增强啊..
 结果都是返回原图..

**Comment by Mona12138** [comment]
Thank you for your reply！I really appreciate your assistance and the time you took to address my issue.
